// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFrALNVtpJqLesxLRDZJJYbFpkySt4WsA',
    appId: '1:973382249906:web:cc8ea7d7223e1c09f408ab',
    messagingSenderId: '973382249906',
    projectId: 'easetour-782d1',
    authDomain: 'easetour-782d1.firebaseapp.com',
    databaseURL: 'https://easetour-782d1-default-rtdb.firebaseio.com',
    storageBucket: 'easetour-782d1.appspot.com',
    measurementId: 'G-1V24F2YR6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVvhZruvxxgerlqSi7rEYTSJVlfob6mjg',
    appId: '1:973382249906:android:bbb9325e6bb560c4f408ab',
    messagingSenderId: '973382249906',
    projectId: 'easetour-782d1',
    databaseURL: 'https://easetour-782d1-default-rtdb.firebaseio.com',
    storageBucket: 'easetour-782d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4SI08KqR6qb9j_02RrbK7aZ6KIb8DHV4',
    appId: '1:973382249906:ios:9f242252ff08837bf408ab',
    messagingSenderId: '973382249906',
    projectId: 'easetour-782d1',
    databaseURL: 'https://easetour-782d1-default-rtdb.firebaseio.com',
    storageBucket: 'easetour-782d1.appspot.com',
    androidClientId: '973382249906-vu7k6npmt7iqt39ngi1q5mdarajdh8a3.apps.googleusercontent.com',
    iosClientId: '973382249906-8qtk32aoc5sufh3atv7k29ro2oe7ssut.apps.googleusercontent.com',
    iosBundleId: 'com.example.easeTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4SI08KqR6qb9j_02RrbK7aZ6KIb8DHV4',
    appId: '1:973382249906:ios:e99721fc20ee350cf408ab',
    messagingSenderId: '973382249906',
    projectId: 'easetour-782d1',
    databaseURL: 'https://easetour-782d1-default-rtdb.firebaseio.com',
    storageBucket: 'easetour-782d1.appspot.com',
    androidClientId: '973382249906-vu7k6npmt7iqt39ngi1q5mdarajdh8a3.apps.googleusercontent.com',
    iosClientId: '973382249906-fhq54g6cjuuoaa6ege08rrbp3g26m0e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.easeTour.RunnerTests',
  );
}
